export const LOAD_PRODUCTS = 'LOAD_PRODUCTS'
export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS'
export const LOAD_PRODUCTS_FAILURE = 'LOAD_PRODUCTS_FAILURE'

export const LOAD_PRODUCT = 'LOAD_PRODUCT'
export const LOAD_PRODUCT_SUCCESS = 'LOAD_PRODUCT_SUCCESS'
export const LOAD_PRODUCT_FAILURE = 'LOAD_PRODUCT_FAILURE'

export const ADD_PRODUCT = 'ADD_PRODUCT'
export const ADD_PRODUCT_DRAWING = 'ADD_PRODUCT_DRAWING'
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_FAILURE = 'ADD_PRODUCT_FAILURE'

// export const RESEND_PRODUCT = 'RESEND_PRODUCT'
// export const RESEND_PRODUCT_SUCCESS = 'RESEND_PRODUCT_SUCCESS'
// export const RESEND_PRODUCT_FAILURE = 'RESEND_PRODUCT_FAILURE'

// export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'
// export const REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS'
// export const REMOVE_PRODUCT_FAILURE = 'REMOVE_PRODUCT_FAILURE'